# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal9611-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a51,$(TARGET_DEVICE)),)

endif
