# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal9611-common/setup-makefiles.sh

DEVICE_MANIFEST_FILE += vendor/samsung/universal9611-common/proprietary/vendor/etc/vintf/manifest/manifest_android.hardware.drm@1.3-service.widevine.xml
